"""
CommentLens — Open-Source YouTube Comment Analyzer
===================================================

Analyze YouTube video comments with AI to extract sentiment, pain points,
feature requests, and praise points. Supports multiple LLM providers.

This is the open-source community edition. For deeper analysis with
executive insights, competitive intelligence, and formatted PDF reports,
visit: https://alex-gmdotcom.github.io/commentlens/

Dependencies:
    pip install customtkinter requests youtube-comment-downloader

Supported Providers:
    Claude | OpenAI | Gemini | DeepSeek | MiniMax
"""

import customtkinter as ctk
import threading
import requests
import json
import re
import csv
import os
import time
import webbrowser
from datetime import datetime
from tkinter import messagebox

# ==========================================
# 1. AI 模型配置
# ==========================================
PROVIDERS = {
    "Claude": {
        "models": ["claude-sonnet-4-5", "claude-haiku-4-5",
                   "claude-3-5-sonnet-20241022", "claude-3-5-haiku-20241022"],
        "placeholder": "sk-ant-api03..."
    },
    "OpenAI": {
        "models": ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "o3-mini"],
        "placeholder": "sk-..."
    },
    "Gemini": {
        "models": ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash"],
        "placeholder": "AIza..."
    },
    "DeepSeek": {
        "models": ["deepseek-chat", "deepseek-reasoner"],
        "placeholder": "sk-..."
    },
    "MiniMax": {
        "models": ["abab6.5s-chat", "abab6.5-chat", "MiniMax-M2.7", "MiniMax-Text-01"],
        "placeholder": "eyJ..."
    }
}

# 报告语言配置
REPORT_LANGUAGES = {
    "中文 (Chinese)": "zh",
    "English": "en",
}

# I18N 双语标签
I18N = {
    "zh": {
        "report_title": "CommentLens 分析报告",
        "sentiment_title": "📊 情感分布 (Sentiment Breakdown)",
        "pain_title": "🔥 核心痛点 (Pain Points)",
        "feature_title": "💡 需求与建议 (Feature Requests)",
        "praise_title": "⭐ 用户好评亮点 (Praise Points)",
        "footer": "Generated by CommentLens (Open Source Edition)",
        "positive": "正面 Positive",
        "negative": "负面 Negative",
        "neutral": "中性 Neutral",
        "mixed": "混合 Mixed",
        "mentions": "提及次数",
        "cta_title": "📈 需要更深度的分析？",
        "cta_body": "开源版提供基础分析能力。如需执行摘要、归因分析、行动清单、竞品洞察等深度报告，请访问",
        "cta_link_text": "alex-gmdotcom.github.io/commentlens",
    },
    "en": {
        "report_title": "CommentLens Analysis Report",
        "sentiment_title": "📊 Sentiment Breakdown",
        "pain_title": "🔥 Pain Points",
        "feature_title": "💡 Feature Requests",
        "praise_title": "⭐ Praise Points",
        "footer": "Generated by CommentLens (Open Source Edition)",
        "positive": "Positive",
        "negative": "Negative",
        "neutral": "Neutral",
        "mixed": "Mixed",
        "mentions": "Mentions",
        "cta_title": "📈 Need deeper analysis?",
        "cta_body": "The open-source edition covers the basics. For executive summaries, attribution analysis, action checklists, and competitive intelligence, visit",
        "cta_link_text": "alex-gmdotcom.github.io/commentlens",
    }
}

# 开源版评论上限
MAX_COMMENTS_OPEN = 50

# ==========================================
# 2. 工具函数
# ==========================================

def extract_json(raw_text):
    """鲁棒的 JSON 提取,处理 LLM 常见的输出问题"""
    if not raw_text:
        raise ValueError("AI 返回内容为空")

    text = raw_text.strip()

    # 1. 移除 markdown 代码围栏
    text = re.sub(r'^```(?:json|JSON)?\s*\n?', '', text)
    text = re.sub(r'\n?```\s*$', '', text)
    text = text.strip()

    # 2. 直接尝试解析
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # 3. 用正则提取最大的 {...} 块
    match = re.search(r'\{[\s\S]*\}', text)
    if not match:
        raise ValueError(f"无法定位 JSON 对象，AI 原始输出前 200 字: {raw_text[:200]}...")

    candidate = match.group(0)

    # 4. 直接解析提取出的块
    try:
        return json.loads(candidate)
    except json.JSONDecodeError:
        pass

    # 5. 修复 trailing comma
    fixed = re.sub(r',(\s*[\]}])', r'\1', candidate)
    try:
        return json.loads(fixed)
    except json.JSONDecodeError:
        pass

    # 6. 截断恢复:逐步缩短结尾找最大可解析前缀
    for cut_point in range(len(candidate) - 1, max(len(candidate) - 2000, 100), -1):
        truncated = candidate[:cut_point]
        balance_braces = truncated.count('{') - truncated.count('}')
        balance_brackets = truncated.count('[') - truncated.count(']')
        if balance_braces >= 0 and balance_brackets >= 0:
            attempt = truncated.rstrip().rstrip(',') + ']' * balance_brackets + '}' * balance_braces
            try:
                return json.loads(attempt)
            except json.JSONDecodeError:
                continue

    raise ValueError(f"无法解析 JSON（已尝试所有兜底策略）。原始输出前 300 字: {raw_text[:300]}...")


# ==========================================
# 3. HTML 报告生成 (开源版: 基础报告)
# ==========================================

def generate_html_report(product_name, video_url, all_analyses, report_summary,
                         output_path, lang="zh"):
    """生成开源版 HTML 报告 — 基础分析,不含深度洞察模块"""

    t = I18N.get(lang, I18N["zh"])

    def esc(s):
        if s is None:
            return ""
        return (str(s).replace("&", "&amp;").replace("<", "&lt;")
                .replace(">", "&gt;").replace('"', "&quot;"))

    sb = report_summary.get("sentiment_breakdown", {})
    pains = report_summary.get("pain_points_ranked", []) or []
    feats = report_summary.get("feature_requests_ranked", []) or []
    praises = report_summary.get("praise_points_ranked", []) or []

    total = sum(sb.get(k, 0) for k in ["positive", "negative", "neutral", "mixed"])

    def pct(v):
        return f"{v / total * 100:.0f}%" if total > 0 else "0%"

    def sev_color(s):
        return {"critical": "#dc2626", "high": "#f97316",
                "medium": "#eab308", "low": "#64748b"}.get(s, "#64748b")

    def prio_color(p):
        return {"P0": "#dc2626", "P1": "#f97316", "P2": "#eab308"}.get(p, "#64748b")

    # --- 痛点卡片 ---
    pain_html = ""
    for i, p in enumerate(pains[:8]):
        quotes_html = ""
        for q in (p.get("representative_quotes") or [])[:2]:
            quotes_html += f'<div style="font-size:12px;color:#94a3b8;font-style:italic;border-left:2px solid #334155;padding-left:8px;margin-top:6px;">"{esc(q)}"</div>'

        pain_html += f"""<div class='card border-red'>
            <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;flex-wrap:wrap;">
                <span style="font-size:22px;font-weight:900;color:#334155;">#{i+1}</span>
                <strong style='color:#fca5a5;'>{esc(p.get('pain_point',''))}</strong>
                <span style="background:{sev_color(p.get('severity','low'))};color:white;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:bold;">{esc((p.get('severity') or 'low').upper())}</span>
            </div>
            <small style="color:#94a3b8;">{esc(p.get('description',''))}</small>
            {quotes_html}
            <span class='badge'>{t['mentions']}: {p.get('mention_count', p.get('total_mentions', 0))}</span>
        </div>"""

    # --- 需求卡片 ---
    feat_html = ""
    for i, f in enumerate(feats[:8]):
        feat_html += f"""<div class='card border-blue'>
            <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;flex-wrap:wrap;">
                <span style="font-size:22px;font-weight:900;color:#334155;">#{i+1}</span>
                <strong style='color:#93c5fd;'>{esc(f.get('feature',''))}</strong>
                <span style="background:{prio_color(f.get('priority','P2'))};color:white;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:bold;">{esc(f.get('priority','P2'))}</span>
            </div>
            <small style="color:#94a3b8;">{esc(f.get('description',''))}</small>
            <span class='badge'>{t['mentions']}: {f.get('mention_count', f.get('total_mentions', 0))}</span>
        </div>"""

    # --- 好评卡片 ---
    praise_html = ""
    for i, pr in enumerate(praises[:6]):
        praise_html += f"""<div class='card border-green'>
            <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;flex-wrap:wrap;">
                <span style="font-size:22px;font-weight:900;color:#334155;">#{i+1}</span>
                <strong style='color:#86efac;'>{esc(pr.get('praise', pr.get('praise_point','')))}</strong>
            </div>
            <small style="color:#94a3b8;">{esc(pr.get('description',''))}</small>
            <span class='badge'>{t['mentions']}: {pr.get('mention_count', pr.get('total_mentions', 0))}</span>
        </div>"""

    # --- CTA 模块 ---
    cta_html = f"""
    <div class='card' style='border-top:3px solid #f59e0b; background:rgba(245,158,11,0.03);'>
        <h3 style="color:#fbbf24;">{t['cta_title']}</h3>
        <p style="color:#cbd5e1;font-size:14px;line-height:1.7;">
            {t['cta_body']}
            <a href="https://alex-gmdotcom.github.io/commentlens/" style="color:#f59e0b;font-weight:bold;" target="_blank">{t['cta_link_text']}</a>
        </p>
        <div style="margin-top:12px;display:flex;gap:12px;flex-wrap:wrap;">
            <span style="background:#1e293b;padding:6px 12px;border-radius:6px;font-size:12px;color:#94a3b8;">✅ Executive Summary</span>
            <span style="background:#1e293b;padding:6px 12px;border-radius:6px;font-size:12px;color:#94a3b8;">✅ Attribution Analysis</span>
            <span style="background:#1e293b;padding:6px 12px;border-radius:6px;font-size:12px;color:#94a3b8;">✅ Action Checklist</span>
            <span style="background:#1e293b;padding:6px 12px;border-radius:6px;font-size:12px;color:#94a3b8;">✅ Competitive Intelligence</span>
            <span style="background:#1e293b;padding:6px 12px;border-radius:6px;font-size:12px;color:#94a3b8;">✅ 500+ Comments</span>
        </div>
    </div>"""

    lang_attr = "zh-CN" if lang == "zh" else "en"

    html = f"""
    <!DOCTYPE html>
    <html lang="{lang_attr}">
    <head>
        <meta charset="UTF-8">
        <title>{t['report_title']} - {esc(product_name)}</title>
        <style>
            body {{ font-family: 'Segoe UI', system-ui, sans-serif; background-color: #0a0e17; color: #e2e8f0; margin: 0; padding: 40px; }}
            h1, h2, h3 {{ color: #ffffff; }}
            .container {{ max-width: 1100px; margin: 0 auto; }}
            .header {{ border-bottom: 1px solid #1e293b; padding-bottom: 20px; margin-bottom: 24px; }}
            .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }}
            .card {{ background: #111827; border: 1px solid #1e293b; padding: 20px; border-radius: 12px; margin-bottom: 20px; line-height: 1.5; }}
            .border-red {{ border-top: 3px solid #ef4444; }}
            .border-blue {{ border-top: 3px solid #3b82f6; }}
            .border-green {{ border-top: 3px solid #22c55e; }}
            .badge {{ background: #1e293b; padding: 4px 8px; border-radius: 4px; font-size: 12px; margin-top: 10px; display: inline-block; color: #94a3b8; }}
            .footer {{ text-align: center; margin-top: 40px; color: #64748b; font-size: 12px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>📊 {t['report_title']}: {esc(product_name)}</h1>
                <p style="color: #94a3b8;">Video: <a href="{esc(video_url)}" style="color: #3b82f6;" target="_blank">{esc(video_url)}</a> | {len(all_analyses)} comments analyzed</p>
            </div>

            <div class="card">
                <h3>{t['sentiment_title']}</h3>
                <div style="display:flex; gap:16px; flex-wrap:wrap; margin-top:12px;">
                    <div style="flex:1; min-width:120px; background:#052e16; border-radius:10px; padding:16px; text-align:center;">
                        <div style="font-size:28px; font-weight:900; color:#22c55e;">{sb.get('positive', 0)}</div>
                        <div style="font-size:12px; color:#86efac;">{t['positive']}</div>
                        <div style="font-size:11px; color:#4ade80;">{pct(sb.get('positive', 0))}</div>
                    </div>
                    <div style="flex:1; min-width:120px; background:#2d1215; border-radius:10px; padding:16px; text-align:center;">
                        <div style="font-size:28px; font-weight:900; color:#ef4444;">{sb.get('negative', 0)}</div>
                        <div style="font-size:12px; color:#fca5a5;">{t['negative']}</div>
                        <div style="font-size:11px; color:#f87171;">{pct(sb.get('negative', 0))}</div>
                    </div>
                    <div style="flex:1; min-width:120px; background:#1e293b; border-radius:10px; padding:16px; text-align:center;">
                        <div style="font-size:28px; font-weight:900; color:#94a3b8;">{sb.get('neutral', 0)}</div>
                        <div style="font-size:12px; color:#cbd5e1;">{t['neutral']}</div>
                        <div style="font-size:11px; color:#94a3b8;">{pct(sb.get('neutral', 0))}</div>
                    </div>
                    <div style="flex:1; min-width:120px; background:#1c1a07; border-radius:10px; padding:16px; text-align:center;">
                        <div style="font-size:28px; font-weight:900; color:#eab308;">{sb.get('mixed', 0)}</div>
                        <div style="font-size:12px; color:#fde047;">{t['mixed']}</div>
                        <div style="font-size:11px; color:#facc15;">{pct(sb.get('mixed', 0))}</div>
                    </div>
                </div>
            </div>

            <div class="grid">
                <div>
                    <h3>{t['pain_title']}</h3>
                    {pain_html}
                </div>
                <div>
                    <h3>{t['feature_title']}</h3>
                    {feat_html}
                </div>
            </div>

            <h3>{t['praise_title']}</h3>
            <div class="grid">
                {praise_html}
            </div>

            {cta_html}

            <div class="footer">
                💡 CSV data exported to same directory for manual review.<br>
                {t['footer']}
            </div>
        </div>
    </body>
    </html>
    """

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)


# ==========================================
# 4. 主应用 GUI
# ==========================================

class CommentLensApp(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.title("CommentLens — Open Source YouTube Comment Analyzer")
        self.geometry("1200x800")
        ctk.set_appearance_mode("dark")
        ctk.set_default_color_theme("blue")

        self.config_path = os.path.join(os.path.expanduser("~"), ".commentlens_config.json")
        self.config_data = self.load_config()

        default_provider = self.config_data.get("last_provider", "Claude")
        if default_provider not in PROVIDERS:
            default_provider = "Claude"

        self.yt_url_var = ctk.StringVar()
        self.max_comments_var = ctk.StringVar(value=str(MAX_COMMENTS_OPEN))
        self.product_name_var = ctk.StringVar()
        self.ai_provider_var = ctk.StringVar(value=default_provider)
        self.ai_model_var = ctk.StringVar(value=PROVIDERS[default_provider]["models"][0])
        self.ai_key_var = ctk.StringVar()

        default_lang = self.config_data.get("last_report_language", "中文 (Chinese)")
        if default_lang not in REPORT_LANGUAGES:
            default_lang = "中文 (Chinese)"
        self.report_language_var = ctk.StringVar(value=default_lang)

        # 恢复保存的 API Key
        saved_key = self.config_data.get("api_keys", {}).get(default_provider, "")
        if saved_key:
            self.ai_key_var.set(saved_key)

        self.setup_ui()

    def load_config(self):
        try:
            with open(self.config_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except:
            return {"api_keys": {}}

    def save_config(self):
        try:
            with open(self.config_path, "w", encoding="utf-8") as f:
                json.dump(self.config_data, f, ensure_ascii=False, indent=2)
        except:
            pass

    def setup_ui(self):
        main_frame = ctk.CTkFrame(self)
        main_frame.pack(fill="both", expand=True, padx=10, pady=10)

        left_frame = ctk.CTkFrame(main_frame, width=400)
        left_frame.pack(side="left", fill="y", padx=(0, 10), pady=0)
        left_frame.pack_propagate(False)

        right_frame = ctk.CTkFrame(main_frame)
        right_frame.pack(side="right", fill="both", expand=True)

        # --- Section 1: YouTube ---
        ctk.CTkLabel(left_frame, text="1. YouTube 视频", font=("Arial", 16, "bold")).pack(anchor="w", pady=(10, 5), padx=10)
        ctk.CTkEntry(left_frame, textvariable=self.yt_url_var, placeholder_text="YouTube 视频 URL").pack(fill="x", padx=10, pady=(5, 0))

        comments_frame = ctk.CTkFrame(left_frame, fg_color="transparent")
        comments_frame.pack(fill="x", padx=10, pady=(5, 0))
        ctk.CTkLabel(comments_frame, text="最大评论数:").pack(side="left")
        max_entry = ctk.CTkEntry(comments_frame, textvariable=self.max_comments_var, width=80)
        max_entry.pack(side="left", padx=(5, 0))
        ctk.CTkLabel(comments_frame, text=f"(开源版上限 {MAX_COMMENTS_OPEN})", text_color="gray", font=("Arial", 11)).pack(side="left", padx=(5, 0))

        ctk.CTkEntry(left_frame, textvariable=self.product_name_var, placeholder_text="产品名称 (如 JetKVM, 不要用品牌名)").pack(fill="x", padx=10, pady=(5, 0))
        ctk.CTkLabel(left_frame, text="💡 请填具体产品名 (如 'JetKVM')，不要填品牌名 (如 'Xiaomi')", text_color="gray", font=("Arial", 11)).pack(anchor="w", padx=10, pady=(0, 10))

        # --- Section 2: AI Settings ---
        ctk.CTkLabel(left_frame, text="2. AI 设置", font=("Arial", 16, "bold")).pack(anchor="w", pady=(10, 5), padx=10)
        ctk.CTkOptionMenu(left_frame, variable=self.ai_provider_var, values=list(PROVIDERS.keys()), command=self.on_provider_change).pack(fill="x", padx=10, pady=(5, 0))
        self.model_menu = ctk.CTkOptionMenu(left_frame, variable=self.ai_model_var, values=PROVIDERS[self.ai_provider_var.get()]["models"])
        self.model_menu.pack(fill="x", padx=10, pady=(5, 0))
        ctk.CTkEntry(left_frame, textvariable=self.ai_key_var, placeholder_text="AI API Key (输入后自动记忆)", show="*").pack(fill="x", padx=10, pady=(5, 0))
        ctk.CTkLabel(left_frame, text="💡 API Key 会自动记忆，下次无需重复输入。", text_color="gray", font=("Arial", 11)).pack(anchor="w", padx=10, pady=(0, 10))

        # --- Section 3: Report Language ---
        ctk.CTkLabel(left_frame, text="3. 报告语言 (Report Language)", font=("Arial", 16, "bold"), text_color="#f59e0b").pack(anchor="w", pady=(10, 5), padx=10)
        ctk.CTkOptionMenu(left_frame, variable=self.report_language_var, values=list(REPORT_LANGUAGES.keys())).pack(fill="x", padx=10, pady=(5, 0))
        ctk.CTkLabel(left_frame, text="💡 仅影响 AI 生成的洞察文字。原始评论保持原文不变。", text_color="gray", font=("Arial", 11), justify="left").pack(anchor="w", padx=10, pady=(0, 10))

        # --- Start Button ---
        self.start_btn = ctk.CTkButton(left_frame, text="🚀 开始分析", height=40, font=("Arial", 14, "bold"), command=self.start_pipeline)
        self.start_btn.pack(fill="x", padx=10, pady=(20, 10))

        # --- Progress ---
        self.progress_bar = ctk.CTkProgressBar(left_frame)
        self.progress_bar.pack(fill="x", padx=10, pady=(0, 5))
        self.progress_bar.set(0)

        self.status_label = ctk.CTkLabel(left_frame, text="就绪", text_color="gray")
        self.status_label.pack(anchor="w", padx=10)

        # --- Pro Upgrade Hint ---
        ctk.CTkLabel(left_frame, text="━" * 40, text_color="#1e293b").pack(padx=10, pady=(15, 5))
        ctk.CTkLabel(left_frame, text="📈 需要更深度的分析?", font=("Arial", 13, "bold"), text_color="#f59e0b").pack(anchor="w", padx=10)
        ctk.CTkLabel(left_frame, text="执行摘要 · 归因分析 · 行动清单 · 竞品洞察\n500+ 评论 · 格式化 PDF 报告\n→ alex-gmdotcom.github.io/commentlens", text_color="gray", font=("Arial", 11), justify="left").pack(anchor="w", padx=10, pady=(2, 10))

        # --- Log Area ---
        ctk.CTkLabel(right_frame, text="📋 运行日志", font=("Arial", 14, "bold")).pack(anchor="w", padx=10, pady=(10, 5))
        self.log_box = ctk.CTkTextbox(right_frame, state="disabled", font=("Consolas", 12))
        self.log_box.pack(fill="both", expand=True, padx=10, pady=(0, 10))

    def on_provider_change(self, provider):
        models = PROVIDERS[provider]["models"]
        self.model_menu.configure(values=models)
        self.ai_model_var.set(models[0])
        saved_key = self.config_data.get("api_keys", {}).get(provider, "")
        self.ai_key_var.set(saved_key)

    def log(self, msg):
        self.log_box.configure(state="normal")
        self.log_box.insert("end", msg + "\n")
        self.log_box.see("end")
        self.log_box.configure(state="disabled")

    def set_progress(self, value):
        self.progress_bar.set(value)

    def start_pipeline(self):
        url = self.yt_url_var.get().strip()
        product = self.product_name_var.get().strip()
        api_key = self.ai_key_var.get().strip()
        provider = self.ai_provider_var.get()

        if not url or not product or not api_key:
            messagebox.showerror("缺少信息", "请填写 YouTube URL、产品名称和 API Key")
            return

        # 品牌名警告
        brand_names = ["Xiaomi", "Apple", "Google", "Samsung", "Sony", "Microsoft",
                       "Huawei", "DJI", "Lenovo", "小米", "苹果", "华为", "三星"]
        if product in brand_names:
            if not messagebox.askyesno("品牌名警告",
                    f"'{product}' 看起来是品牌名而非产品名。\n\n"
                    f"品牌名会导致分析失焦。请改用具体产品名，如：\n"
                    f"  ✅ 'Xiaomi Mi Band 9'\n"
                    f"  ✅ 'iPhone 16 Pro'\n\n"
                    f"确定继续使用 '{product}' 吗？"):
                return

        # 保存配置
        if "api_keys" not in self.config_data:
            self.config_data["api_keys"] = {}
        self.config_data["api_keys"][provider] = api_key
        self.config_data["last_provider"] = provider
        self.config_data["last_report_language"] = self.report_language_var.get()
        self.save_config()

        self.start_btn.configure(state="disabled")
        threading.Thread(target=self.run_pipeline_thread, daemon=True).start()

    def call_llm(self, system_prompt, user_prompt, max_retries=3):
        provider = self.ai_provider_var.get()
        model = self.ai_model_var.get()
        api_key = self.ai_key_var.get()

        for attempt in range(max_retries):
            try:
                if provider == "Claude":
                    url = "https://api.anthropic.com/v1/messages"
                    headers = {
                        "x-api-key": api_key,
                        "content-type": "application/json",
                        "anthropic-version": "2023-06-01"
                    }
                    payload = {
                        "model": model,
                        "max_tokens": 4096,
                        "system": system_prompt,
                        "messages": [{"role": "user", "content": user_prompt}]
                    }
                    resp = requests.post(url, headers=headers, json=payload)
                    resp.raise_for_status()
                    return resp.json()["content"][0]["text"]

                elif provider == "OpenAI":
                    url = "https://api.openai.com/v1/chat/completions"
                    headers = {
                        "Authorization": f"Bearer {api_key}",
                        "Content-Type": "application/json"
                    }
                    payload = {
                        "model": model,
                        "messages": [
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt}
                        ],
                        "max_tokens": 4096
                    }
                    resp = requests.post(url, headers=headers, json=payload)
                    resp.raise_for_status()
                    return resp.json()["choices"][0]["message"]["content"]

                elif provider == "DeepSeek":
                    url = "https://api.deepseek.com/v1/chat/completions"
                    headers = {
                        "Authorization": f"Bearer {api_key}",
                        "Content-Type": "application/json"
                    }
                    payload = {
                        "model": model,
                        "messages": [
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt}
                        ],
                        "max_tokens": 4096
                    }
                    resp = requests.post(url, headers=headers, json=payload)
                    resp.raise_for_status()
                    return resp.json()["choices"][0]["message"]["content"]

                elif provider == "Gemini":
                    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
                    payload = {
                        "contents": [{"parts": [{"text": f"{system_prompt}\n\n{user_prompt}"}]}],
                        "generationConfig": {"maxOutputTokens": 4096}
                    }
                    resp = requests.post(url, json=payload)
                    resp.raise_for_status()
                    return resp.json()["candidates"][0]["content"]["parts"][0]["text"]

                elif provider == "MiniMax":
                    url = "https://api.minimax.chat/v1/text/chatcompletion_v2"
                    headers = {
                        "Authorization": f"Bearer {api_key}",
                        "Content-Type": "application/json"
                    }
                    payload = {
                        "model": model,
                        "messages": [
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt}
                        ]
                    }
                    resp = requests.post(url, headers=headers, json=payload)
                    resp.raise_for_status()
                    data = resp.json()
                    base_resp = data.get("base_resp", {})
                    if base_resp.get("status_code", 0) != 0:
                        raise Exception(f"MiniMax error: {base_resp.get('status_msg', 'Unknown')}")
                    return data["choices"][0]["message"]["content"]

            except Exception as e:
                self.log(f"  ⚠️ 第 {attempt+1} 次请求失败: {str(e)[:100]}")
                if attempt < max_retries - 1:
                    wait = 2 ** (attempt + 1)
                    if "429" in str(e):
                        wait = 30
                    self.log(f"  等待 {wait} 秒后重试...")
                    time.sleep(wait)
                else:
                    raise

    def run_pipeline_thread(self):
        try:
            yt_url = self.yt_url_var.get()
            max_limit = min(int(self.max_comments_var.get() or MAX_COMMENTS_OPEN), MAX_COMMENTS_OPEN)
            product_name = self.product_name_var.get()
            report_lang_key = self.report_language_var.get()
            report_lang = REPORT_LANGUAGES.get(report_lang_key, "zh")
            lang_label = "Simplified Chinese (简体中文)" if report_lang == "zh" else "English"

            timestamp = datetime.now().strftime("%Y%m%d_%H%M")

            # ========== 阶段 1: 抓评论 ==========
            self.log("=" * 50)
            self.log(f"🔍 阶段 1: 抓取评论 (上限 {max_limit} 条)")
            self.set_progress(0.1)

            from youtube_comment_downloader import YoutubeCommentDownloader, SORT_BY_POPULAR
            downloader = YoutubeCommentDownloader()
            comments = []
            for i, comment in enumerate(downloader.get_comments_from_url(yt_url, sort_by=SORT_BY_POPULAR)):
                if i >= max_limit:
                    break
                comments.append({
                    "index": i + 1,
                    "author": comment.get("author", ""),
                    "text": comment.get("text", "").strip(),
                    "likes": comment.get("votes", "0"),
                })

            self.log(f"  ✅ 成功抓取 {len(comments)} 条评论")
            self.set_progress(0.2)

            if not comments:
                self.log("❌ 未抓取到评论，请检查 URL")
                self.start_btn.configure(state="normal")
                return

            # ========== 阶段 2: 批量 AI 分析 ==========
            self.log(f"\n🤖 阶段 2: AI 批量分析 ({self.ai_provider_var.get()} / {self.ai_model_var.get()})")

            batch_size = 40
            all_analyses = []
            all_batch_summaries = []

            for batch_idx in range(0, len(comments), batch_size):
                batch = comments[batch_idx:batch_idx + batch_size]
                batch_num = batch_idx // batch_size + 1
                total_batches = (len(comments) + batch_size - 1) // batch_size
                self.log(f"  📦 分析第 {batch_num}/{total_batches} 批 ({len(batch)} 条)...")

                ct = "\n".join([f"[#{j+1}] (👍{c['likes']}) {c['author']}: {c['text']}" for j, c in enumerate(batch)])

                # 开源版 prompt: 基础分析,不含归因/建议
                sys_prompt = f"""You are a product analyst reading YouTube comments about '{product_name}'.

Distinguish between three layers of comments:
  1. PRODUCT FEEDBACK — about the actual product '{product_name}'
  2. META FEEDBACK — about the YouTuber, video, sponsorship, reviewer bias. NOT product feedback.
  3. OFF-TOPIC — jokes, greetings, irrelevant tangents

Only PRODUCT FEEDBACK should yield pain_points or feature_requests.

Return ONLY pure JSON, no markdown fences."""

                user_prompt = f"""Analyze these YouTube comments about '{product_name}'. Return ONLY this JSON:
{{
  "comments_analysis": [
    {{
      "index": 1,
      "sentiment": "positive|negative|neutral|mixed",
      "category": "pain_point|feature_request|praise|question|meta_comment|off_topic",
      "pain_points": ["short tag"],
      "feature_requests": ["short tag"],
      "summary_zh": "一句话概括（15字以内）"
    }}
  ],
  "batch_summary": {{
    "top_pain_points": [{{"pain_point": "...", "mention_count": 0}}],
    "top_feature_requests": [{{"feature": "...", "mention_count": 0}}]
  }}
}}

Rules:
- comments_analysis array must match input length ({len(batch)} items)
- If category is meta_comment or off_topic, set pain_points and feature_requests to []
- Tags should be 2-6 words, in comment's language

Comments:
{ct}"""

                try:
                    raw = self.call_llm(sys_prompt, user_prompt)
                    result = extract_json(raw)
                    batch_analyses = result.get("comments_analysis", [])
                    batch_summary = result.get("batch_summary", {})
                    all_analyses.extend(batch_analyses)
                    all_batch_summaries.append(batch_summary)
                    self.log(f"    ✅ 第 {batch_num} 批完成 ({len(batch_analyses)} 条)")
                except Exception as e:
                    self.log(f"    ❌ 第 {batch_num} 批 API 分析失败: {str(e)[:150]}")
                    # 填充失败批次
                    for c in batch:
                        all_analyses.append({
                            "index": c["index"], "sentiment": "neutral",
                            "category": "off_topic", "pain_points": [],
                            "feature_requests": [], "summary_zh": "API分析失败"
                        })

                progress = 0.2 + 0.5 * (batch_idx + len(batch)) / len(comments)
                self.set_progress(min(progress, 0.7))

            # ========== 阶段 3: 综合报告 ==========
            self.log(f"\n📊 阶段 3: 生成综合报告...")
            self.set_progress(0.75)

            # 计算情感分布
            sentiment_counts = {"positive": 0, "negative": 0, "neutral": 0, "mixed": 0}
            for a in all_analyses:
                s = a.get("sentiment", "neutral")
                if s in sentiment_counts:
                    sentiment_counts[s] += 1

            # 开源版最终报告 prompt: 不含反直觉发现/归因/行动清单/竞品洞察
            final_sys_prompt = f"""You are a product analyst writing a summary report on '{product_name}'.

Output language: {lang_label}. ALL text content must be in {lang_label}.

Return ONLY pure JSON, no markdown fences."""

            aggregated_data = json.dumps({
                "total_comments": len(all_analyses),
                "sentiment_counts": sentiment_counts,
                "batch_summaries": all_batch_summaries,
            }, ensure_ascii=False)

            final_user_prompt = f"""Synthesize the batch analyses below into a final report on '{product_name}'.

Output JSON structure:
{{
  "sentiment_breakdown": {{
    "positive": {sentiment_counts["positive"]},
    "negative": {sentiment_counts["negative"]},
    "neutral": {sentiment_counts["neutral"]},
    "mixed": {sentiment_counts["mixed"]}
  }},
  "pain_points_ranked": [
    {{
      "rank": 1,
      "pain_point": "Clear name",
      "severity": "critical|high|medium|low",
      "mention_count": 0,
      "description": "1-2 sentence explanation",
      "representative_quotes": ["original quote"]
    }}
  ],
  "feature_requests_ranked": [
    {{
      "rank": 1,
      "feature": "Clear name",
      "priority": "P0|P1|P2",
      "mention_count": 0,
      "description": "1-2 sentence explanation"
    }}
  ],
  "praise_points_ranked": [
    {{
      "rank": 1,
      "praise": "Clear name",
      "mention_count": 0,
      "description": "1-2 sentence explanation"
    }}
  ]
}}

Rules:
- pain_points_ranked: max 8 items, ranked by mention_count desc
- feature_requests_ranked: max 8 items
- praise_points_ranked: max 6 items

Batch summaries:
{aggregated_data}"""

            try:
                raw_report = self.call_llm(final_sys_prompt, final_user_prompt)
                report_summary = extract_json(raw_report)
                self.log("  ✅ 综合报告生成成功")
            except Exception as e:
                self.log(f"  ❌ 综合报告生成失败: {e}")
                report_summary = {
                    "sentiment_breakdown": sentiment_counts,
                    "pain_points_ranked": [],
                    "feature_requests_ranked": [],
                    "praise_points_ranked": [],
                }

            self.set_progress(0.85)

            # ========== 阶段 4: 导出 ==========
            self.log(f"\n💾 阶段 4: 导出文件...")

            safe_name = re.sub(r'[^\w\-]', '_', product_name)
            base_dir = os.path.join(os.path.expanduser("~"), "Desktop")
            if not os.path.isdir(base_dir):
                base_dir = os.path.expanduser("~")

            html_path = os.path.join(base_dir, f"CommentLens_Report_{safe_name}_{timestamp}.html")
            csv_path = os.path.join(base_dir, f"CommentLens_Data_{safe_name}_{timestamp}.csv")

            # 导出 HTML
            generate_html_report(product_name, yt_url, all_analyses,
                                 report_summary, html_path, lang=report_lang)
            self.log(f"  📄 HTML 报告: {html_path}")

            # 导出 CSV
            with open(csv_path, "w", encoding="utf-8-sig", newline="") as f:
                writer = csv.writer(f)
                writer.writerow(["Index", "Author", "Text", "Likes", "Sentiment",
                                 "Category", "Pain Points", "Feature Requests", "Summary"])
                for i, a in enumerate(all_analyses):
                    c = comments[i] if i < len(comments) else {}
                    writer.writerow([
                        a.get("index", i + 1),
                        c.get("author", ""),
                        c.get("text", ""),
                        c.get("likes", ""),
                        a.get("sentiment", ""),
                        a.get("category", ""),
                        "; ".join(a.get("pain_points", [])),
                        "; ".join(a.get("feature_requests", [])),
                        a.get("summary_zh", ""),
                    ])
            self.log(f"  📊 CSV 数据: {csv_path}")

            self.set_progress(1.0)
            self.status_label.configure(text="✅ 分析完成!")
            self.log(f"\n{'=' * 50}")
            self.log(f"✅ 完成！已分析 {len(all_analyses)} 条评论")
            self.log(f"{'=' * 50}")

            # 自动打开报告
            webbrowser.open(f"file://{os.path.abspath(html_path)}")

        except Exception as e:
            self.log(f"\n❌ 运行出错: {str(e)}")
            import traceback
            self.log(traceback.format_exc())
        finally:
            self.start_btn.configure(state="normal")


# ==========================================
# 5. 入口
# ==========================================

if __name__ == "__main__":
    app = CommentLensApp()
    app.mainloop()
